apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-agency-backend 
  template:
    metadata:
      labels:
        app: travel-agency-backend
    spec:
      containers:
      - name: backend
        image: ${REGISTRY_LOGIN_SERVER}/travel-agency-backend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: travel-agency-backend-service
spec:
  type: ClusterIP
  selector:
    app: travel-agency-backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-agency-frontend
  template:
    metadata:
      labels:
        app: travel-agency-frontend
    spec:
      containers:
      - name: frontend
        image: ${REGISTRY_LOGIN_SERVER}/travel-agency-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: travel-agency-frontend-service
spec:
  type: ClusterIP
  selector:
    app: travel-agency-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
