name: Build and Deploy to AKS via ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/travel-agency-frontend:latest ./frontend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/travel-agency-frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/travel-agency-backend:latest ./backend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/travel-agency-backend:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment/backend-deployment.yaml
          kubectl apply -f deployment/frontend-deployment.yaml
