# This workflow will build and test your project
# Name the workflow as you like
name: Travel Agency CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          npm test || echo "No backend tests defined"
      - name: Run frontend tests
        run: |
          cd frontend
          npm test || echo "No frontend tests defined"
      - name: Build backend Docker image
        run: |
          docker build -t travel-agency-backend ./backend
      - name: Build frontend Docker image
        run: |
          docker build -t travel-agency-frontend ./frontend
      - name: Snyk scan backend Docker image
        uses: snyk/actions/docker@master
        with:
          image: travel-agency-backend
          args: --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk scan frontend Docker image
        uses: snyk/actions/docker@master
        with:
          image: travel-agency-frontend
          args: --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run backend container and check health
        run: |
          docker run -d -p 5000:5000 --name backend-test travel-agency-backend
          sleep 30
          curl --fail http://localhost:5000/api/travel
      - name: Print backend container logs on failure
        if: failure()
        run: docker logs backend-test || true
      - name: Run frontend container and check health
        run: |
          docker run -d -p 3000:3000 --name frontend-test travel-agency-frontend
          sleep 20
          curl --fail http://localhost:3000
      - name: Cleanup containers
        if: always()
        run: |
          docker rm -f backend-test || true
          docker rm -f frontend-test || true
